### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by blegat** [jump-dev/SDPA.jl#3]
- [ ] Use patches in the build script so that they can be reused in OBS.
- [ ] Create a SDPA package in [OBS science project](https://build.opensuse.org/project/show/science)
- [ ] Create a SDPA package in [OBS windows:mingw:win64 project](https://build.opensuse.org/project/show/windows:mingw:win64)
- [ ] Create a SDPA package in [OBS windows:mingw:win32 project](https://build.opensuse.org/project/show/windows:mingw:win32)
- [ ] Install them via [WinRPM](https://github.com/JuliaPackaging/WinRPM.jl)

**EDIT** these steps are outdated now that we use BinaryBuilder

**Comment by odow** [comment]
SDPA.jl works on Windows.
