### ISSUE TITLE
Use newer version of CxxWrap

### ISSUE THREAD

**Issue by schillic** [jump-dev/SDPA.jl#62]
Currently, SDPA fails on PkgEval:

[PkgEval run](https://juliaci.github.io/NanosoldierReports/pkgeval_badges/S/SDPA.html)

The culprit seems to be CxxWrap. However, CxxWrap alone runs fine:

[PkgEval run](https://juliaci.github.io/NanosoldierReports/pkgeval_badges/C/CxxWrap.html)

I think simply supporting a newer version (v0.16 or maybe even only v0.15) would solve that.
On this note, I suggest to [reactivate CompatHelper](https://github.com/jump-dev/SDPA.jl/actions/workflows/CompatHelper.yml).

**Comment by odow** [comment]
This is never trivial because we need to rebuild SDPA_jll etc:
https://github.com/JuliaPackaging/Yggdrasil/pull/9694

I dislike CompatHelper. People should release fewer breaking changes.
